---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install pipenv
          command: |
            python3 -m pip install pipenv --user

      - run:
          name: install deps
          command: |
            pipenv install --dev --deploy

      - run:
          name: run tests
          command: |
            pipenv run python -m pytest .

      - run:
          name: run mypy
          command: |
            pipenv run mypy jab/ --ignore-missing-imports --strict

      - run:
          name: ensure black format
          command: |
            pipenv run black -l 110 . --check

      - run:
          name: code coverage
          command: |
            pipenv run python -m pytest --cov-report=xml --cov=jab/ test/

      - run:
          name: codecov upload
          command: |
            pipenv install codecov
            pipenv run codecov
